### ISSUE TITLE
Does sign() use the public or the private key?

### ISSUE THREAD

**Issue by bestia-dev** [nresare/ssh-agent-client-rs#23]
The sign() function should use the private key as I understand.
When connecting to ssh server it sends a "message".
The client uses ssh-agent to sign this "message" with the private key.
The server uses the public key to confirm, that the signature was signed with the private key.
Only the owner of the private key can make this signature, therefor he is authenticated.

What is the use-case for signing with the public key?

**Comment by nresare** [comment]
You are right, that the signature is made with a private key and the wording of the documentation of the sign() method is wrong. The public key is provided along with the message to sign to the ssh-agent, and is used to identify the private key that should be used to create the signature. I will update the documentation shortly

**Comment by nresare** [comment]
I have released a new version of the crate and updated the documentation to hopefully make this clearer
