### ISSUE TITLE
The private/public keys must be in PEM format.

### ISSUE THREAD

**Issue by bestia-dev** [nresare/ssh-agent-client-rs#24]
I had my ssh keys generated with ssh-keygen and  by default it makes 2 files:  
`~/.ssh/github_com_ssh_1` 
and 
`~/.ssh/github_com_ssh_1.pub`

It looks like ssh-agent-client-rs does not like these formats.  
I tried to use the sign() function without success.
The same keys must be converted into the PEM format.

I converted the private key  
Warning: It will replace the same file ! SO make the copy first.

```bash
cp ~/.ssh/github_com_ssh_1 ~/.ssh/github_com_ssh_1.priv
ssh-keygen -p -m PEM -f ~/.ssh/github_com_ssh_1
cp ~/.ssh/github_com_ssh_1 ~/.ssh/github_com_ssh_1.priv.pem
mv ~/.ssh/github_com_ssh_1.priv ~/.ssh/github_com_ssh_1
```

I converted the public key

```bash
ssh-keygen -e -m PEM -f ~/.ssh/github_com_ssh_1.pub  > ~/.ssh/github_com_ssh_1.pub.pem
```

Now I added this new formats of the same key to ssh-agent
```bash
ssh-add -t 1h ~/.ssh/github_com_ssh_1.priv.pem
```

And all works fine. 
It signs the "message" with the `private key` that is inside the ssh-agent.
Great. Thanks.

**Comment by nresare** [comment]
The `ssh-agent-client-rs` crate leans on the [ssh-key](https://github.com/RustCrypto/SSH/tree/master/ssh-key) crate to deal with parsing ssh-keys, so any trouble you might have turning some key file in some specific format into a `PrivateKey` or `PublicKey` struct for use with this crate is better directed to that project.

That said, if you look at the tests in [codec.rs](https://github.com/nresare/ssh-agent-client-rs/blob/main/src/codec.rs#L325) there are some examples of code successfully reading both public and private ssh keys as they are generated by ssh-keygen (where private keys are in PEM format and public keys are in the openssh single line format.
